/*
 * This source file was generated by the Gradle 'init' task
 */
package com.inventory.updater;



public class App { // App contains only core application logic : https://docs.gradle.org/current/userguide/best_practices_structuring_builds.html


    public static void main(String[] args) {
    }
}
