/*
 * This source file was generated by the Gradle 'init' task
 */
package com.inventory.updater;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

public class App { // App contains only core application logic : https://docs.gradle.org/current/userguide/best_practices_structuring_builds.html

    //TODO: Move this to some utility subproject but right now we dun care
    public Properties getProperties() {
        Properties props = new Properties();

            try (InputStream fin = getClass().getResourceAsStream("/shopify.properties")) {
                props.load(fin);
            } catch (IOException ex) {
            System.getLogger(App.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }


        return props;
    }

    public static void main(String[] args) {
        System.out.println(new App().getProperties());
    }
}
